/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileFilter;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DungX
 */
public class MoveFrame extends javax.swing.JFrame {

  private String srcFolder;
  private String desFolder;
  
  private List<String> srcFiles = new ArrayList<>();
  
  
  /**
   * Creates new form MoveFrame
   */
  public MoveFrame() {
    initComponents();
    setDefaultLookAndFeelDecorated(true);
    initListeners();
  }

  private void initListeners() {
    initJListListener();
  }
  
  private void initJListListener() {
    listSrcMedia.addListSelectionListener(new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
          loadImagePreview();
        }
      }
    });
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    btnDesBrowse = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    txtDesFolder = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    listDesMedia = new javax.swing.JList<>();
    btnDesRename = new javax.swing.JButton();
    btnDesDelete = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    lblDesPreview = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    txtDesName = new javax.swing.JTextArea();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    btnSrcBrowse = new javax.swing.JButton();
    txtSrcFolder = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    listSrcMedia = new javax.swing.JList<>();
    btnSrcMove = new javax.swing.JButton();
    btnSrcDelete = new javax.swing.JButton();
    jLabel7 = new javax.swing.JLabel();
    lblSrcPreview = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    txtSrcName = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Resources Mover");

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "To", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

    jLabel3.setText("Source folder");

    btnDesBrowse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnDesBrowse.setText("Browse");

    jLabel4.setText("Folder path:");

    jScrollPane2.setViewportView(listDesMedia);

    btnDesRename.setText("Rename");

    btnDesDelete.setText("Delete");

    jLabel8.setText("Preview");

    lblDesPreview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    txtDesName.setColumns(20);
    txtDesName.setLineWrap(true);
    txtDesName.setRows(5);
    jScrollPane4.setViewportView(txtDesName);

    org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel2Layout.createSequentialGroup()
        .add(5, 5, 5)
        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel2Layout.createSequentialGroup()
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel4)
              .add(jLabel3))
            .add(18, 18, 18)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jPanel2Layout.createSequentialGroup()
                .add(btnDesBrowse)
                .add(0, 0, Short.MAX_VALUE))
              .add(txtDesFolder))
            .addContainerGap())
          .add(jPanel2Layout.createSequentialGroup()
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jPanel2Layout.createSequentialGroup()
                .add(38, 38, 38)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                    .add(lblDesPreview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(22, 22, 22))
                  .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                    .add(jLabel8)
                    .add(78, 78, 78))
                  .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      .add(btnDesRename)
                      .add(btnDesDelete))
                    .add(56, 56, 56))))
              .add(jPanel2Layout.createSequentialGroup()
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel2Layout.createSequentialGroup()
        .add(16, 16, 16)
        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3)
          .add(btnDesBrowse))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4)
          .add(txtDesFolder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel2Layout.createSequentialGroup()
            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(btnDesRename)
            .add(13, 13, 13)
            .add(btnDesDelete)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 114, Short.MAX_VALUE)
            .add(jLabel8)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(lblDesPreview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(jScrollPane2))
        .addContainerGap())
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "From", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

    jLabel1.setText("Source folder");

    jLabel2.setText("Folder path:");

    btnSrcBrowse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnSrcBrowse.setText("Browse");
    btnSrcBrowse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSrcBrowseActionPerformed(evt);
      }
    });

    jScrollPane1.setViewportView(listSrcMedia);

    btnSrcMove.setText("Move");

    btnSrcDelete.setText("Delete");

    jLabel7.setText("Preview");

    lblSrcPreview.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    lblSrcPreview.setIconTextGap(0);

    txtSrcName.setColumns(20);
    txtSrcName.setLineWrap(true);
    txtSrcName.setRows(5);
    jScrollPane3.setViewportView(txtSrcName);

    org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel3Layout.createSequentialGroup()
        .add(5, 5, 5)
        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel3Layout.createSequentialGroup()
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel2)
              .add(jLabel1))
            .add(18, 18, 18)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(btnSrcBrowse)
              .add(txtSrcFolder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 273, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(0, 0, Short.MAX_VALUE))
          .add(jPanel3Layout.createSequentialGroup()
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(jPanel3Layout.createSequentialGroup()
                    .add(81, 81, 81)
                    .add(jLabel7))
                  .add(jPanel3Layout.createSequentialGroup()
                    .add(27, 27, 27)
                    .add(lblSrcPreview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                  .add(jPanel3Layout.createSequentialGroup()
                    .add(64, 64, 64)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      .add(btnSrcDelete)
                      .add(btnSrcMove))))
                .add(784, 784, 784))
              .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(772, 772, 772))))))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel3Layout.createSequentialGroup()
        .add(16, 16, 16)
        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(btnSrcBrowse))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(txtSrcFolder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(18, 18, 18)
        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel3Layout.createSequentialGroup()
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(btnSrcMove)
            .add(62, 62, 62)
            .add(btnSrcDelete)
            .add(62, 62, 62)
            .add(jLabel7)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
            .add(lblSrcPreview, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(jScrollPane1))
        .addContainerGap())
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(12, 12, 12)
        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 384, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(18, 18, 18)
        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(24, Short.MAX_VALUE))
    );

    jPanel2.getAccessibleContext().setAccessibleName("Destination Folder");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSrcBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrcBrowseActionPerformed
    selectFile();
  }//GEN-LAST:event_btnSrcBrowseActionPerformed

  public void selectFile() {
      JFileChooser chooser = new JFileChooser();
      
      // optionally set chooser options ...
      chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
          File f = chooser.getSelectedFile();
          if (f.isDirectory()) {
            srcFolder = f.getAbsolutePath();
            txtSrcFolder.setText(srcFolder);
            FilenameFilter imageFilter = new FilenameFilter() {
              @Override
              public boolean accept(File dir, String name) {
                return name.matches("$.[(png)(jpg)(xml)]");
              }
            };
            
            File[] subDirs = f.listFiles();
            HashMap<String, String> filesMap = new HashMap<>();
            
            for (File dir: subDirs) {
              
                File[] files = dir.listFiles();
              for (File file: files) {
                if (!filesMap.containsKey(file.getName())) {
                  filesMap.put(file.getName(), file.getAbsolutePath());
                }
              }
            
            }
            String[] fileNames = new String[filesMap.keySet().size()];
            filesMap.keySet().toArray(fileNames);
            
            srcFiles.clear();
            srcFiles = new ArrayList(filesMap.values());
            listSrcMedia.setListData(fileNames);
          }
      } else {
          // user changed their mind
      }
  }
  
  private void loadImagePreview() {
    int selectedIdx = listSrcMedia.getSelectedIndex();
    
    if (srcFiles.size() > selectedIdx) {
      // Load preview image
      BufferedImage bufferedImage = null;
      try {
        bufferedImage = ImageIO.read(new File(srcFiles.get(selectedIdx)));
        Image image = bufferedImage.getScaledInstance(lblSrcPreview.getWidth(), lblSrcPreview.getHeight(), Image.SCALE_SMOOTH);
        lblSrcPreview.setIcon(new ImageIcon(image));
      } catch (IOException ex) {
        Logger.getLogger(MoveFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
      
      
      // Load name to textfield
      txtSrcName.setText((new File(srcFiles.get(selectedIdx))).getName());
    }
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MoveFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDesBrowse;
  private javax.swing.JButton btnDesDelete;
  private javax.swing.JButton btnDesRename;
  private javax.swing.JButton btnSrcBrowse;
  private javax.swing.JButton btnSrcDelete;
  private javax.swing.JButton btnSrcMove;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JLabel lblDesPreview;
  private javax.swing.JLabel lblSrcPreview;
  private javax.swing.JList<String> listDesMedia;
  private javax.swing.JList<String> listSrcMedia;
  private javax.swing.JTextField txtDesFolder;
  private javax.swing.JTextArea txtDesName;
  private javax.swing.JTextField txtSrcFolder;
  private javax.swing.JTextArea txtSrcName;
  // End of variables declaration//GEN-END:variables
}
